Add the os to docker tags
drone-plugins/drone-codacy pull request #4
Opened 2018-01-23 22:24 UTC by tboerger

As requested at https://github.com/drone-plugins/drone-codecov/issues/7

2018-01-24 08:24 UTC, appleboy requested changes

2018-01-24 08:24 UTC, appleboy commented on .appveyor.yml
>            docker push plugins/codacy:windows
missing `-amd64`

2018-01-24 08:35 UTC, tboerger commented on .appveyor.yml
>            docker push plugins/codacy:windows
Wrong line, but fixed.

2018-02-18 10:04 UTC, appleboy approved these changes

2018-02-18 10:04 UTC, merged